services:
  prometheus:
    labels:
      - traefik.enable=true
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
      - traefik.http.routers.prometheus.rule=Host(`${HOST:-prometheus-127-0-0-1.nip.io}`)
    networks:
      - traefik

networks:
  traefik:
    name: traefik
