services:
  portainer:
    labels:
      - traefik.enable=true
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.rule=Host(`${HOST:-portainer-127-0-0-1.nip.io}`)
      - traefik.http.routers.portainer.entrypoints=http,https
      - traefik.http.routers.portainer.tls.certresolver=le
    networks:
      - traefik

networks:
  traefik:
    name: traefik
