set-ports:
	echo COMPOSE_FILE=docker-compose.yml:docker-compose.ports.yml > .env

set-traefik-http:
	echo COMPOSE_FILE=docker-compose.yml:docker-compose.traefik-http.yml > .env

set-traefik-https:
	echo COMPOSE_FILE=docker-compose.yml:docker-compose.traefik-https.yml > .env
