name: minio
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2021-11-05T09-16-26Z
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: asdfasdf
      # MINIO_BROWSER_REDIRECT_URL: https://minio.example.com
    volumes:
      - minio-data:/data
volumes:
  minio-data:
